databases:
  - name: web
    databaseName: web
    user: web
  
services:
  - type: web # On ne change pas ceci, ceci reste 'web'
    name: web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn web.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: web
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
